# Install environment
name: Install environment

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      install-script:
        required: true
        type: string
jobs:
  install-env:
    name: Install env (${{ inputs.os }}, ${{ inputs.python-version }})
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
    - name: Setup pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}-${{ hashFiles('**/requirements*.txt') }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Perform pip installation
      shell: bash -l {0}
      run: |
        cd misc
        . ./${{ inputs.install-script }}
