# reusable workflow to run tests on different installation types and OS
name: Run unit tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      test-script:
        required: true
        type: string
jobs:
  run-unit-tests:
    name: Unit tests (${{ inputs.os }}, ${{ inputs.python-version }})
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: ${{ inputs.python-version }}
    - name: Run tests
      shell: bash -l {0}
      run: |
        cd tests
        . ./${{ inputs.test-script }}
