name: code-review

on:
  pull_request:
    types: [labeled]

jobs:
  get-code-review:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'code-review')
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install openai pygithub

      - name: Run OpenAI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODE_REVIEW_PROMPT: ${{ secrets.CODE_REVIEW_PROMPT }}
          CODE_REVIEW_SYSTEM_MESSAGE: ${{ secrets.CODE_REVIEW_SYSTEM_MESSAGE }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python .github/scripts/openai_code_review.py
